stages:
  - build
  - deploy
docker-img:
  stage: build
  script:
    - >
      ENV=${TARGET_ENV};
      if [[ -z ${ENV} ]];
      then
        ENV="dev";
      fi
      export TAG=$(sed 's/.*"version": "\(.*\)".*/\1/;t;d' ./package.json);
      echo "building image nearmi-${ENV}/app:${TAG}";
      eval docker build -f ./docker/Dockerfile -t nearmi-${ENV}/app:${TAG} .;
      echo "Cleaning dangling images";
      eval docker image rmi -f $(docker images -f "dangling=true" -q);
  tags:
    - shell
docker-pull:
  stage: deploy
  script:
    -
