image: node:lts
variables:
  APP_IMAGE_NAME: 'nearmi.registry/nearmi/app'
cache:
  paths:
    - ./node_modules
  key: 'nearmi_app_node'

stages:
  - test
  - package
  - deploy

test:
  stage: test
  script:
    - echo "running test for app..."
  tags:
    - kubernetes
package:
  script:
    - npm ci --silent
    - chmod -R +x ./node_modules/.bin
    - export PATH=$(pwd)/node_modules/.bin:$PATH
    - echo $PATH
    - npm  install react-scripts@3.4.1 -g --silent
    - npm run build --timing || true
    - ls -lart ./build
    - echo "archiving..."
  artifacts:
    paths:
      - ./build
    expire_in: 1 days
  tags:
    - kubernetes
deploy:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  stage: deploy
  before_script:
    - cp /conf/nearmiRootCA.crt /kaniko/ssl/certs/
  script:
    - |
      echo "building and deploying image to nexus"
      TAG=$(sed 's/.*"version": "\(.*\)".*/\1/;t;d' ./package.json)
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"nearmi.registry\":{\"username\":\"${NEXUS_LOGIN}\",\"password\":\"${NEXUS_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --build-arg VERSION="${TAG}" --destination ${APP_IMAGE_NAME}:${TAG}
  tags:
    - kubernetes
