// ACCOUNT TYPE
export const LNG_CHANGE = 'LNG_CHANGE';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const ANONYMOUS = 'ANONYMOUS';
// SHOP TYPE
export const NEXT_SHOP_CREATION_STEP = 'NEXT_SHOP_CREATION_STEP';
export const HANDLED_NEXT_SHOP_CREATION_STEP =
  'HANDLED_NEXT_SHOP_CREATION_STEP';
