// ACCOUNT TYPE
export const LNG_CHANGE = 'LNG_CHANGE';
export const TOOLBAR_MENU_ICON_DISPLAY = 'TOOLBAR_MENU_ICON_DISPLAY';
export const TOOLBAR_MENU_ICON_TOGGLED = 'TOOLBAR_MENU_ICON_TOGGLED';
export const TOOLBAR_MENU_ICON_HANDLED = 'TOOLBAR_MENU_ICON_HANDLED';
export const UPDATE_LOADING = 'UPDATE_LOADING';
// SHOP TYPE
export const NEXT_SHOP_CREATION_STEP = 'NEXT_SHOP_CREATION_STEP';
export const HANDLED_NEXT_SHOP_CREATION_STEP =
  'HANDLED_NEXT_SHOP_CREATION_STEP';
export const RESTORE_FORM_VALUE = 'RESTORE_FORM_VALUE';
export const RESTORE_FORM_VALUE_COMPLETED = 'RESTORE_FORM_VALUE_COMPLETED';
export const ADDRESS_UPDATED = 'ADDRESS_UPDATED';
export const CREATE_SHOP = 'CREATE_SHOP';
export const UPDATE_MANAGED_SHOP = 'UPDATE_MANAGED_SHOP';
export const SHOP_CONFIG_LOADED = 'SHOP_CONFIG_LOADED';
export const UPDATE_VISITIED_SHOP = 'UPDATE_VISITIED_SHOP';
